### ISSUE TITLE
ef57.cc does not compile for ARM with GCC

### ISSUE THREAD

**Issue by olupton** [openxla/xla#8247]
https://github.com/openxla/xla/commit/49f45a12bcca8edc7f215887dbb112b2639d8a97 introduced an implementation of `xla::ConvertF64ToEf57` for arm64 neon that does not compile with GCC: https://godbolt.org/z/aYfds9Y15. cc: @majnemer.

**Comment by mattbarrett98** [comment]
@penpornk wasn't this issue fixed here https://github.com/openxla/xla/commit/bdb43468cc106b3f61771801f9d31fc398a22883?

**Comment by Mountagha** [comment]
@penpornk can I work on this as a newcommer ;)

**Comment by kredd2506** [comment]
Hi, I'm interested in picking this up. Before I start, I wanted to confirm — commit [bdb43468cc](https://github.com/openxla/xla/commit/bdb43468cc106b3f61771801f9d31fc398a22883) ("Fix OSS clang build") fixed a similar vector conversion issue for clang but appears to be specific to clang, not GCC. Can someone confirm this issue is still present with GCC on ARM?

**Comment by allanrenucci** [comment]
>@penpornk wasn't this issue fixed here https://github.com/openxla/xla/commit/bdb43468cc106b3f61771801f9d31fc398a22883?

I believe so. Closing.
